name: Build and Upload APK

on:
  push:
    branches: [ v2 ]  # 或者你的主分支名称
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Add signing properties
      env:
         SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}
      run: |
          echo ${{ secrets.SIGNING_PROPERTIES }} > encoded_signing_properties
          base64 -d -i encoded_signing_properties > signing.properties

    - name: Add jks file
      run: |
          echo ${{ secrets.SIGN_KEY }} > ./encoded_key
          base64 -d -i encoded_key > key.jks

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleRelease  #  构建 debug APK，你可以改为 assembleRelease 构建 release 版本
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-apk  # 你可以自定义 artifact 的名字
        path: app/build/outputs/apk/release/*.apk # 替换为你的 APK 输出路径
    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"
    - name: Publish Pre-Release
      uses: softprops/action-gh-release@v2
      with:
         files: |
            app/build/outputs/apk/release/*.apk
         tag_name: ${{ steps.timestamp.outputs.tag }}
         release_name: Release ${{ steps.timestamp.outputs.tag }}
